### PR TITLE
[WIP] Texture Support

### LINKED ISSUE #218: Add Support for Textures
I'm planning on tackling this soon, as I'd like to incorporate texture loading for use in `meshrender` (my work-in-progress OpenGL mesh renderer and viewer). Will start work in my fork in `BerkeleyAutomation` and run it by you once a PR is ready.

One thought -- should we start by supporting multiple textures per mesh, or is it okay for now to just support a single texture?

### PR DESCRIPTION
**Pull request by mikedh**
Opening a PR to track progress; this is slowly getting there. Fixes #218 

- [x] `TextureVisual` object
- [ ] Finalize `TextureVisuals` data structure (multiple materials? manage UV for multiple materials?)
- [x] `Material` Objects: PBR, Basic
- [ ] Finalize `Material` data structure
- [X] Assets resolver for file system, ZIP, and remote
- [x] OBJ load texture
- [x] UV/Texture to color
- [x] GLTF load texture
- [x] GLTF exports don't crash on texture
- [x] PLY load texture
- [x] Figure out why PLY textures are mapping wrong
- [x] Pyglet viewer show texture

### Post-PR Scope
- GLTF export texture
- PLY export texture
- OBJ export texture
- shaders for PBR in pyglet viewer `trimesh.viewer.windowed`

Other major changes: `trimesh.io` and `trimesh.path.io` renamed to `trimesh.exchange` and `trimesh.path.exchange`, as `io` is a builtin library that we were previously stomping on and relying on import precedence. `exchange` isn't so great but is better than anything else I could think of, and is used elsewhere to mean this (Hoops Exchange is basically a bunch of importers/exporters).

### CODE REVIEW

**Comment by mikedh** [comment]
The last thing before merging this is finalizing the data structures for materials and the visual object. I'm fine changing pretty much anything in this PR. Any suggestions @PyryM @wkentaro @mmatl @epicwink?

Note that for textured meshes you want to display, you should call load with `process=False`, as trimesh will otherwise merge vertices, i.e. `trimesh.load('fuze.ply', process=False)` I'm going to keep that as the default behavior, as it would be a large application- breaking change, and it leads to surprise in a different case (i.e. "why isn't this STL watertight?!")

## Texture Data Structure
Loaders which see UV coordinates and images create a `trimesh.visual.TextureVisuals` for `mesh.visual`, instead of a `trimesh.visual.ColorVisuals` object (which holds vertex or face colors). 

### `TextureVisuals`
`visual.uv` : (n, 2) float, UV coordinates. Updated by `update_vertices`. 
`visual.material`: a single material object

### `Materials`
Holds any images and parameters. Currently two simple ones defined, `PBRMaterial` (as from GLTF) and `SimpleMaterial` which just holds an image at the moment, although it might be desirable to hold a few parameters (like ambient/specular/diffuse).

**Comment by mikedh** [comment]
Happy to go back and change things on this, but it is functionally complete, passing CI, and decently well tested so I'm going to merge.

**Comment by wkentaro** [comment]
@mikedh So, current implementation does not support multiple mtllib and Kd section in mtl?

**Comment by wkentaro** [comment]
Maybe we should change TextureVisuals to support multiple uv, map_Kd and Kd?

**Comment by mikedh** [comment]
Ah, it definitely wasn't intentional, I just didn't have any files like that in my tests haha. What were you thinking in terms of architecture?

Also, I wonder if SceneNet would be willing to re-license a few files that demonstrate these cases as MIT, just so we could include them directly in our test model set and have CI run on them.

**Comment by wkentaro** [comment]
Previously, I set `Trimesh.visual.vertex_colors` extracting colors from multiple materials to visualize ShapeNetSem models in https://github.com/mikedh/trimesh/pull/272#issue-238880772.
But now `Trimesh.visual` is `TextureVisuals` instead of `ColorVisuals`, and not sure. Where should I check if I want to know how the `Trimesh.visual` is used by opengl?

**Comment by mikedh** [comment]
Hey, sorry just saw this. The conversion to a vertex list is [here](https://github.com/mikedh/trimesh/blob/master/trimesh/rendering.py#L84-L98)

The material -> pyglet texture is [called from here](https://github.com/mikedh/trimesh/blob/master/trimesh/viewer/windowed.py#L182-L187) and the logic is [here](https://github.com/mikedh/trimesh/blob/master/trimesh/rendering.py#L250-L266)

I'm honestly a little hazy on how multiple UV coordinates and images get drawn... I guess multiple draws with the different images and coordinates set? Or as another vertex_list entirely?

**Comment by mmatl** [comment]
Hi Mike,

Just read through the future goals for this, and if you're planning on setting up PBR shaders, feel free to cannibalize the code from my re-worked branch of Meshrender [here](https://github.com/BerkeleyAutomation/meshrender/tree/revision/meshrender). I re-wrote it to be as close as possible to glTF standards. If you're interested, we could try to move some of the viewer/renderer code over to trimesh to fulfill the need for a PBR-based shader. There are still a few work-in-progress things, including environment IBL and point light shadow mapping, but it works pretty well so far!

Best,
Matt

**Comment by mikedh** [comment]
@mmatl Holy crap that is freaking awesome! Not that I'm surprised, but it actually worked for me the first time haha. That's so much better than `trimesh.viewer.windowed` I'm not even sure it's even worth backporting. Great work! I am also super on board with "just do what GLTF does" train.  

My major technical question was, "don't PyOpenGL and pyglet fight each other?" but neither seem to mind haha. I have to think about it a bit more, but it seems like some of the options to get that goodness into "more hands more easily":  
1) `meshrender` becomes a pip trimesh[all] dependency, and `trimesh.viewer.__init__` checks to see if `meshrender` is installed and replaces `trimesh.viewer.windowed` with the equivalent if available. Probably would mean removing the dependency on `autolab_core` and `perception`
2) `meshrender` becomes a submodule in `trimesh`, like `trimesh.viewer.advanced` (or something)
3) Backporting the `meshrender` shader magic into `trimesh.viewer.windowed`

What were your plans/goals for it? Also, after implementing that any thoughts on the materials and texture data models?

Obligatory dope  `DamagedHelmet` screenshot loaded with `trimesh` and displayed using your viewer :stuck_out_tongue:
damagedhelmet

**Comment by mikedh** [comment]
Oh @wkentaro I got approved for the ShapeNet models and all 30gb of them are downloading tonight, I'll try to take a look at the multi-material issue you were seeing.

**Comment by wkentaro** [comment]
> Oh @wkentaro I got approved for the ShapeNet models and all 30gb of them are downloading tonight, I'll try to take a look at the multi-material issue you were seeing.

Sounds good! Thanks! I'm also working on this today.

**Comment by mmatl** [comment]
@mikedh Happy you pulled a working version haha! It's under heavy active development but I should be done in a day or two (or at least to a point where it's well-documented and I'm happy with it).

To respond to the question about PyOpenGL and pyglet fighting: they actually are designed to interop! The author of `PyOpenGL` made sure that it worked with `pyglet` and they play nicely together. I could maybe try to just use `pyglet`'s GL wrappers, but I found that `PyOpenGL` had better code coverage and is better maintained.

With regards to the options you proposed, I'm tending to think that option (1) is probably easiest. `meshrender` will definitely be easily pip-installable, so I think it makes the most sense. My plan is to make it as lightweight as possible -- dependencies are going to be simply the following:

- `freetype-py`: For loading/processing fonts (it's lightweight and cross-platform pip installable)
- `imageio`: For GIF I/O when recording things from the viewer.
- `networkx`: For scene graph
- `numpy`
- `Pillow`
- `pyglet`
- `PyOpenGL`
- `PyOpenGL_accelerate`
- `six`
- `trimesh`

So it's basically just what you already have, plus `six`, `imageio`, and `freetype` (and the OpenGL stuff).

Excited about getting this into people's hands! Let me know what you think.

**Comment by math-sasso** [comment]
@mikedh have you created a practical way to export the obj or glb files with the texture?
I am trying to follow the issues to find the answer, but nothing worked to me yet

**Pull request merged**
