### PR TITLE
Support MTL and UV unwarping to vertex_colors for Wavefront

### PR DESCRIPTION
**Pull request by wkentaro**
screen shot 2018-12-02 at 4 36 59

```python
#!/usr/bin/env python

import pprint

import trimesh


mesh = trimesh.load('./fuze.obj')

print('mesh.metadata:')
pprint.pprint(mesh.metadata)

print('mesh.visual.vertex_colors:')
print(mesh.visual.vertex_colors)

mesh.show()
```

## Output of above script

```bash
% python load_fuze.py
mesh.metadata:
{'file_name': 'fuze.obj',
 'file_path': '/Users/wkentaro/Documents/xxx/python/src/trimesh/models/fuze.obj',
 'mtllibs': [{'filename': '/Users/wkentaro/Documents/xxx/python/src/trimesh/models/./fuze.o
bj.mtl',
              'map_Kd': 'fuze_uv.jpg',
              'newmtl': 'material_0'}],
 'processed': True,
 'vertex_texture': array([[0.629012, 0.417026],
       [0.629012, 0.442966],
       [0.661437, 0.404056],
       ...,
       [0.565363, 0.991709],
       [0.148287, 0.971874],
       [0.520901, 0.780556]])}
mesh.visual.vertex_colors:
[[153   5  41 255]
 [127 127 127 255]
 [103  29  46 255]
 ...
 [161  11  56 255]
 [158   3   9 255]
 [163 111   2 255]]
```

### CODE REVIEW

**Comment by wkentaro** [comment]
This is the result of a mesh with higher resolution.

screen shot 2018-12-02 at 4 42 11

**Comment by mikedh** [comment]
Awesome! Texture is a bear, it would be great to incrementally start getting stuff into trimesh. I just moved around some files and refactored slightly with some of the ideas from #218 into the [`texture`](https://github.com/mikedh/trimesh/tree/texture) branch to collect texture changes. The layout is currently:

- visuals/resolvers.py
  - includes tools to resolve and read assets (like MTL files, texture images, etc). It's not always easy to figure out where the assets are relative to the file you're loading, and in the case of ZIP archives, cloud files, or http in load_remote, you need to handle it differently. 
- visuals/colors.py
  - has ColorVisuals object (moved and renamed trimesh/visual.py)
- visuals/texture.py
  - has TextureVisuals object (not implemented) and utility functions (like `uv_to_color`)

What do you think? @mmatl  @PyryM  @EpicWink any 'puts'?

I think your `_get_vertex_colors` is generally useful and doesn't have to be OBJ- specific. Would you mind moving it into `/visuals/texture.py` in the `texture` branch? I'd probably change the API for it to:

```
def uv_to_color(uv, image):
    """
    Get the color in a texture image.
	
    Parameters
    -------------
    uv : (n, 2) float
      UV coordinates on texture image
    image : PIL.Image
      Texture image

    Returns
    ----------
    colors : (n, 4) float
      RGBA color at each of the UV coordinates
    """
```

Then the question of "where the heck are the assets" is answered elsewhere. Thanks for the PR!

**Comment by wkentaro** [comment]
It sounds good. So what should I need to do exactly?
I just need to move `uv_to_color` to `visuals/texture.py`?

**Comment by mikedh** [comment]
Yeah that would be great then I'll merge it into texture. I was thinking of keeping `texture` out of master for a month or so until the MVP feature list in #218 is done 

Thanks!
Mike

**Comment by wkentaro** [comment]
I updated the commit as following. Could you review again?

- rebased,
- added uv_to_color to visual/texture.py
- added test_uv_to_color

**Comment by mikedh** [comment]
Looks good, thanks!

**Pull request merged**
