### PR TITLE
Re-enable fix_inversion

### PR DESCRIPTION
**Pull request by clbarnes**
Some of the code makes the assumption that an inside-out trimesh will have a negative volume. However, this is not true as the `mass_properties` method returns the absolute volume if the mesh looks ok *except* for being inside-out ( https://github.com/mikedh/trimesh/commit/f0394c671a3703e08430ef7cf0c2def2652667a3 ). This means that, for single-body meshes, `fix_inversion` would never do anything.

Additionally, makes a mesh fix its winding when given `validate=True`.

### CODE REVIEW

**Comment by clbarnes** [comment]
Note that `is_volume` will still return `True` for incorrectly (but consistently) wound meshes. Is that desired behaviour?

**Comment by mikedh** [comment]
Thanks for the PR and test! And yeah that's an oops. I am sort of wondering if we shouldn't also remove the "silent `abs`" logic inside `mass_properties`, seems like I planted a minefield and then immediately drove through it.

**Comment by clbarnes** [comment]
Yes, this PR is a bit of a band-aid. Maybe best not to make allowances for nearly-valid meshes if there's no need to, I think trimesh can stand to be a little opinionated!

**Comment by mikedh** [comment]
Sounds good, I stripped out the confusing `abs` logic in `trimesh.base` that was left over from when `validate` was still a "global-ish" property and your new test still passed. I'll release shortly, thanks for the PR!!

**Pull request merged**
