### PR TITLE
[WIP] Toggle axis in SceneViewer

### PR DESCRIPTION
**Pull request by wkentaro**
Toggle axis in the scene with `A`.

kapture 2018-11-22 at 2 04 23

@mikedh I have just tried it out. Do you have some idea how to store the previous state of `scene`, `vertex_list_XXX` in SceneViewer? Or should I add some functionalities like `delete_geometry`?

## Example used above

```python
#!/usr/bin/env python

import numpy as np
import trimesh
import trimesh.transformations as tf


scene = trimesh.Scene()

# plane
plane = trimesh.creation.box(
    extents=[1, 1, 0.01], face_colors=[0.5, 0.5, 0.5, 0.5]
)
node_name = scene.add_geometry(plane)

# object-1 (box)
box = trimesh.creation.box(extents=[0.3, 0.3, 0.3], face_colors=[0, 1, 0, 0.5])
translation = tf.translation_matrix([-0.2, 0, 0.15 + 0.01])
rotation = tf.rotation_matrix(np.deg2rad(30), [0, 0, 1], point=box.centroid)
transform = rotation @ translation
node_name = scene.add_geometry(box, transform=transform)

# object-2 (cylinder)
cylinder = trimesh.creation.cylinder(
    radius=0.1, height=0.3, face_colors=[0, 0, 1., 0.5]
)
translation = tf.translation_matrix([0.1, -0.2, 0.15 + 0.01])
node_name = scene.add_geometry(cylinder, transform=translation)

scene.show()
```

### CODE REVIEW

**Comment by mikedh** [comment]
Looks great! This supersedes / closes #257 and #256 right? I think for axis I'd store it as a vertex list but not add it to the scene, I'll check that now. It seems like in general if the viewer can mutate scenes things may get a bit confusing.  I'll merge both to a branch and once CI passes merge into master. Thanks for the PR's!

**Comment by mikedh** [comment]
I made some changes in https://github.com/mikedh/trimesh/tree/camera_merge

Let me know if you have any suggestions, otherwise I'll plan to merge to master and release sometime tomorrow:
- renamed `fxfy` -> `focal` and `fovxy` -> `fov`
- changed camera properties to use setters
- added 'set from matrix' setter
- changed axis toggle to not mutate scene by creating a separate `vertexlist` when toggled

**Comment by wkentaro** [comment]
Looks better. Thanks!

**Comment by wkentaro** [comment]
I tested the `camera_merge` branch with above example to toggle axis with `A`.
However, it won't work in some reason. Have you tested with the latest code in the branch?

**Comment by mikedh** [comment]
Hey, yeah it's only drawing the world frame. I can add it back to show the frame for every mesh- maybe with a different key?

**Comment by wkentaro** [comment]
I tested and it worked perfectly. Thanks!

**Comment by mikedh** [comment]
Awesome, thanks again for the PR's! Merged into master in https://github.com/mikedh/trimesh/commit/904087b8d7d7fa4cac11ee2614ef63505f731c01 and should be released as soon as the build finishes.

**Comment by wkentaro** [comment]
You’re so responsive and that helps me a lot!

**Pull request merged**
