### PR TITLE
New interface to Manifold3D.

### PR DESCRIPTION
**Pull request by Eric-Vin**
This PR adds an interface to the [Manifold](https://github.com/elalish/manifold) library, using their Python interface, as discussed in this [issue](https://github.com/mikedh/trimesh/issues/1947).

This is a WIP, as I developed it using a locally built wheel and we'll probably want to wait at least till the wheels are pushed to PyPi (Relevant Issue: https://github.com/elalish/manifold/issues/362) for the CI to run the tests properly. At that point I'll be able to add it as an dependency, which I believe should meet the `[easy]` requirements (thanks to the excellent work in https://github.com/elalish/manifold/pull/537).

@mikedh if there's any missing functionality the interface needs to be complete, please let me know. At the moment it passes all tests on my local machine (with the manifold wheel manually installed), including `test_boolean.py` (in which I added manifold as a potential engine).

### CODE REVIEW

**Comment by mikedh** [comment]
Awesome super excited for this!! 

- `trimesh.interfaces` were originally written for moderately janky `subprocess` interfaces to executables. since there's upcoming nice `cibuildwheel` wheel matrices, I'd actually probably build this directly in to `trimesh.boolean`
- if manifold behaves and benchmarks well I'd probably drop the interface boolean functions (especially the openSCAD one, which is now using manifold itself so it seems kinda pointless).

**Comment by Eric-Vin** [comment]
Sounds like a plan! Hopefully this commit addresses everything you listed, and the tests all run on my machine with manifold installed. Please let me know if there's anything else you'd like changed! Once the wheels are released I can revisit the PR to add the dependencies and ensure all the tests are passing on GitHub as well.

**Comment by Eric-Vin** [comment]
@mikedh I think this should be good to review! I was worried we might get issues with meshes like the one in https://github.com/mikedh/trimesh/issues/1974 , but I tested it on my machine and Manifold seems to handle those cases gracefully, so we're probably fine. Please let me know if you have any thoughts!

**Comment by Eric-Vin** [comment]
Hmm, it looks like there are actually conflicts due to black being applied to the main repo. If you'd like I can run black on this branch and hopefully that'll fix things, or you can resolve any conflicts manually when you merge?

**Comment by Eric-Vin** [comment]
Upon further discussion in [this](https://github.com/mikedh/trimesh/issues/1974) issue, it seems like we should establish that a Trimesh object is a valid manifold before calling out to manifold3d. Any thoughts @mikedh ?

**Pull request merged**
