### PR TITLE
followup on closest_point()

### PR DESCRIPTION
**Pull request by dbukenberger**
This method was developed for my specific use-case to compute distances from many points to one triangle. So I just extended some dimensions here and there to generalize it for a list of triangles.
It has less case distinctions and in my tests was a bit faster than the RTCD method - so I thought, you might want to check it out. =)

Here is a sketch that illustrates how the edge-selection works: https://ggbm.at/qfxsevaq

I often use stripped-down versions of NumPy operations for arrays of known size which often perform a lot faster due to less overhead ... like the simpleCross(), normalization with sqrt(dot()), or inner1d() which I think is equivalent to your util.diagonal_dot().

Cheers,
Dennis

### CODE REVIEW

**Comment by mikedh** [comment]
Nice! How does it benchmark compared to the RTCD one now in master? I'll play around with this when I get a chance.

**Comment by dbukenberger** [comment]
In my test cases with random triangles it usually was around 20-30% faster compared to the RTCD version.
However, it seems the cross product computations do not scale that well for large quantities of triangles (>10k).
For my scenario with many points and only one triangle that is not a problem but could become a bottleneck here. 🤔

Furthermore, I missed out on normalizing a set of vectors in my last version - with that line fixed, I get consistent results for my new one and the RTCD version.

**Comment by mikedh** [comment]
Sweet! I did some profiling and light tuning, and I was able to get the RTCD algorithm to be pretty fast (~50% faster than PR). Given how I screwed up the edge cases on this previously, I generally like using the algorithm from the book, although if we saw large performance gains from an approach that benefited from vectorization I'd definitely go for it.

Updates here: https://github.com/mikedh/trimesh/commit/f3607766d89809166d151e52e21a6bddbbbc2f41

Here are some final profiles (from `cProfile`, `pyinstrument` reports similar results) of the two methods compared. The RTCD algorithm, tuned slightly (now in master):

```
         80 function calls in 0.444 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.406    0.406    0.444    0.444 /dropbox/drop/Dropbox/robotics/trimesh/trimesh/triangles.py:518(closest_point)
        6    0.030    0.005    0.030    0.005 {built-in method numpy.core.multiarray.dot}
        2    0.007    0.003    0.007    0.003 {built-in method numpy.core.multiarray.copyto}
        1    0.000    0.000    0.007    0.007 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/numeric.py:94(zeros_like)
        7    0.000    0.000    0.000    0.000 {method 'any' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.000    0.000 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/numeric.py:156(ones)
        7    0.000    0.000    0.000    0.000 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/_methods.py:42(_any)
        7    0.000    0.000    0.000    0.000 {method 'reduce' of 'numpy.ufunc' objects}
        2    0.000    0.000    0.000    0.000 /dropbox/drop/Dropbox/robotics/trimesh/trimesh/util.py:222(is_shape)
        5    0.000    0.000    0.000    0.000 {method 'reshape' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.empty}
        2    0.000    0.000    0.000    0.000 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/numeric.py:504(asanyarray)
        1    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.empty_like}
        5    0.000    0.000    0.000    0.000 /dropbox/drop/Dropbox/robotics/trimesh/trimesh/util.py:188(is_sequence)
       22    0.000    0.000    0.000    0.000 {built-in method builtins.hasattr}
        2    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.array}
        1    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.zeros}
        6    0.000    0.000    0.000    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```


PR algorithm:
```
         99 function calls in 1.003 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.420    0.420    1.003    1.003 /dropbox/drop/Dropbox/robotics/trimesh/trimesh/triangles.py:639(closest_point)
        4    0.088    0.022    0.217    0.054 /dropbox/drop/Dropbox/robotics/trimesh/trimesh/triangles.py:661(<lambda>)
        7    0.180    0.026    0.180    0.026 {method 'reduce' of 'numpy.ufunc' objects}
        2    0.161    0.081    0.176    0.088 /dropbox/drop/Dropbox/robotics/trimesh/trimesh/triangles.py:662(<lambda>)
        4    0.000    0.000    0.139    0.035 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py:49(_wrapfunc)
        4    0.000    0.000    0.129    0.032 {method 'sum' of 'numpy.ndarray' objects}
        4    0.000    0.000    0.129    0.032 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/_methods.py:34(_sum)
        2    0.000    0.000    0.125    0.062 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py:404(repeat)
        2    0.125    0.062    0.125    0.062 {method 'repeat' of 'numpy.ndarray' objects}
        3    0.000    0.000    0.051    0.017 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py:64(_wrapreduction)
        2    0.000    0.000    0.030    0.015 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py:1821(sum)
        1    0.000    0.000    0.022    0.022 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2016(all)
        4    0.014    0.004    0.014    0.004 {built-in method numpy.core.multiarray.array}
        1    0.000    0.000    0.010    0.010 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py:976(argmax)
        1    0.010    0.010    0.010    0.010 {method 'argmax' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.004    0.004 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py:1764(clip)
        1    0.004    0.004    0.004    0.004 {method 'clip' of 'numpy.ndarray' objects}
        8    0.000    0.000    0.000    0.000 {method 'reshape' of 'numpy.ndarray' objects}
        2    0.000    0.000    0.000    0.000 /dropbox/drop/Dropbox/robotics/trimesh/trimesh/util.py:222(is_shape)
        5    0.000    0.000    0.000    0.000 /dropbox/drop/Dropbox/robotics/trimesh/trimesh/util.py:188(is_sequence)
       22    0.000    0.000    0.000    0.000 {built-in method builtins.hasattr}
        2    0.000    0.000    0.000    0.000 /home/mikedh/miniconda/lib/python3.6/site-packages/numpy/core/numeric.py:504(asanyarray)
        4    0.000    0.000    0.000    0.000 {built-in method builtins.getattr}
        1    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.empty_like}
        2    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
        3    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}
        5    0.000    0.000    0.000    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

**Comment by dbukenberger** [comment]
Yep, looks pretty solid now. 👍 Handling the edge and corner cases well and is pretty fast.

I experimented with some more fancy NumPy stuff but overall it couldn't compete with the RTCD approach for large numbers of random triangles.

**Comment by mikedh** [comment]
Sweet! Thanks for checking and PR'ing! It's really nice to get core functions like this optimized and robust.

One thing I thought was interesting that in most of the actual applications I profiled for this, function overhead was a substantial contributor (~10%) to overall performance, specifically `np.ones` vs `[1.0]*count`. Though the biggest factor was optimizing the dot product / sum calls aggressively.

**Pull request closed without merging**
