### PR TITLE
Speed up proximity.signed_distance and add vertex/face attributes to ply export

### PR DESCRIPTION
**Pull request by brucedjones**
Please see individual commits for details.

### CODE REVIEW

**Comment by mikedh** [comment]
Awesome thanks for the PR! When profiling I was seeing a solid 20% speedup on the signed distance change, looks great! 


For the PLY vertex attribute export I had two quick thoughts: first, rather than being passed to the exporter it would be nice if it automatically got the attributes from `mesh.face_attributes` and `mesh.vertex_attributes` if they were populated:
```
In [5]: import trimesh

In [6]: m = trimesh.creation.box()

In [7]: m.vertex_attributes
Out[7]: {}

In [8]: m.face_attributes
Out[8]: {}
```
Although I could see there could be some challenges with data types doing that and if it's not possible we can skip it :smile:. Second, rather than `kwargs.get(___, [])` I'd prefer to add an explicit kwarg like `vertex_attributes=None`, or `include_vertex_attributes=True` so the docstring is easier for people to understand.

**Comment by brucedjones** [comment]
Anythings possible when we write the code :)

Agree that using the existing vertex/face attributes on the mesh makes more sense, I wasn't aware that these were a thing 😳 . Opted to read from those only and not add the keyword args at all.

I made that change, and while I was there I generalized to accept multidimensional attributes. I also wrote some tests this time around.

**Comment by mikedh** [comment]
That's awesome thanks for the PR and test, the attributes change is great! I've heard from multiple people that they like the "bag of vertex and face attributes" paradigm and adding support throughout the library is really nice. 

I might make the additional change in a few weeks moving re-imported attributes back into `mesh.face_attributes` instead of `mesh.metadata['ply_raw']['face']['data']` or if you're feeling ambitious always happy to take additional PR's :smile:.

Merged to master and CI should do the release shortly.

**Comment by brucedjones** [comment]
heh, I seriously considered doing so but unfortunately couldn't justify the time for my current needs.

**Pull request merged**
