### PR TITLE
 Add ply export support for 1) generating ascii ply 2) including vertex normals

### PR DESCRIPTION
**Pull request by vlimit**
Hi,

This is a minor change to allow the generation of ascii ply files + the inclusion of vertex normals. There must be a better way to implement ndtoascii. Happy to learn (I'm not strong on numpy).

Hope the change is of value. Tested a combination of ply formats (vertex/face colours, ascii/binary, w/wo normals and all opened successfully in meshlab.

Thanks,
Stu

### CODE REVIEW

**Comment by mikedh** [comment]
Awesome, thanks! 

1) You may want to replace the custom `ndtoascii` with [`trimesh.util.array_to_string`](https://github.com/mikedh/trimesh/blob/master/trimesh/util.py#L879-L946) as it *might* be faster and avoids implementing some logic in the exporter.
2) Would you mind adding a unit test (maybe in `test_export`) to make sure the vertex normals are surviving the round trip?

This looks like a solid improvement, thanks for the PR!

**Comment by mikedh** [comment]
Actually no worries, I'll add some additional tests/logic. Thanks for the PR!

**Comment by mikedh** [comment]
Included in master as of https://github.com/mikedh/trimesh/commit/f7595e89c2e216baf62e61101dc374fe84e642a2

**Comment by vlimit** [comment]
Thanks for picking up the PR. I have been away from email over the
weekend, so just catching up on this.
Will do as you suggest wrt the stringification (thanks for the tip) and
the unit tests.

**Comment by Guptajakala** [comment]
Hi, is the feature "including vertex normals" already existing in version 3.7.12?
I couldn't export ply file with normals by 
```
mesh = trimesh.Trimesh(vertices=pts, vertex_normals=normals, vertex_colors=colors)
```

**Pull request merged**
