### PR TITLE
Adds face groups to the mesh when wavefront loaders is used.

### PR DESCRIPTION
**Pull request by hoosha**

### CODE REVIEW

**Comment by mikedh** [comment]
Thanks for the PR!

* would you be able to provide an example file that has these keys so I can add it to tests?

* could these 'groups' exist as a metadata property rather than an attribute? it seems like the vast majority of the time (for other file types) it won't be set. Something like:
```
loaded = {'vertices': data[vid].astype(float),
'vertex_normals': data[nid].astype(float),
'faces': faces, 
'metadata': {'face_group' : groups}}
```

**Comment by hoosha** [comment]
Hi 
Sorry for my late response. An example file is attached.
on the second point it would make sense to add it to the meta data as well.
Best,
Hooman

**Comment by mikedh** [comment]
No worries! I don't think that file made it, could you send it directly to my gmail (mik3dh) or link it?

Thanks!
Mike

**Comment by mikedh** [comment]
Thanks for the model! I added it to tests, and those groups properties should be loaded as `mesh.metadata['face_groups']` when available. I included your group loading code in https://github.com/mikedh/trimesh/commit/83aa8f00958a6860a33f084981e69ed82948fdd6

**Comment by hoosha** [comment]
thanks. will fetch your code and test if it works for me in the new way and let you know.
Best,
Hooman

**Pull request closed without merging**
