### PR TITLE
Use pyrender.trackball.Trackball as alternative to Arcball

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/mikedh/trimesh/issues/368#issuecomment-485153083

### CODE REVIEW

**Comment by wkentaro** [comment]
## Before




## After

**Comment by wkentaro** [comment]
## Example Script

```python
#!/usr/bin/env python

import numpy as np
import trimesh
import trimesh.transformations as tf


mesh = trimesh.load('../models/fuze.obj')
scene = trimesh.Scene()
scene.add_geometry(mesh)
scene.set_camera(angles=[np.deg2rad(90), 0, 0])
scene.show()

scene = trimesh.Scene()
for _ in range(10):
    axis = trimesh.creation.axis(0.01)
    axis.apply_translation(np.random.uniform(-0.3, 0.3, (3,)))
    scene.add_geometry(axis)
scene.show()

```

**Comment by mikedh** [comment]
Looks great, thanks! And thanks @mmatl for the nice trackball implementation. 

Only one question about the PR: it now changes the transform of `scene.camera` when you drag the window around, vs before it didn't mutate the scene. Is this desirable? I guess this way you can drag it to where you want, close the window, then save the camera transform. If we are going to mutate the camera transform in the viewer, maybe we should make the keypress `z` call `scene.set_camera`?

**Comment by wkentaro** [comment]
> it now changes the transform of scene.camera when you drag the window around, vs before it didn't mutate the scene. Is this desirable?

I think the desirable situation is that `self.scene.camera` always has the same information as the current view like `self.scene.camera.resolution` is set on `__init__()`.

>  If we are going to mutate the camera transform in the viewer, maybe we should make the keypress z call scene.set_camera?

This is because `self.scene` can change, isn't it? So `z` key sets default camera pose more dynamically instead of resetting to the fixed camera pose.

**Comment by mikedh** [comment]
Makes sense! Thanks for the PR!

**Comment by wkentaro** [comment]
> we should make the keypress z call scene.set_camera?

I sent PR for this.
https://github.com/mikedh/trimesh/pull/383/files

**Pull request merged**
