### PR TITLE
Adding metadata field primitive with value True to geometries loaded …

### PR DESCRIPTION
**Pull request by ibozhilov**
…from GLTF primitives.

### CODE REVIEW

**Comment by mikedh** [comment]
Thanks for the PR! 

- it would be nice if the flag was *always* populated rather than sometimes true and sometimes nonexistent
- could we add the full explanation/backstory for the flag somewhere, something like: "Some GLTF meshes include more than one primitive, which translates to multiple Trimesh objects. This flag being True indicates that this Trimesh object was one of multiple GLTF primitives under a single GLTF mesh." Maybe a rename to something like `from_gltf_multiprimitive_mesh`, or `from_gltf_primitive` (not sure if either of those are clearer).

**Comment by ibozhilov** [comment]
Usually I go with no default value for such kind of meta, but having default value will be more consistent with the trimesh philosophy, so I have set the meta to be False by default. I have also change the key to `from_gltf_primitive` as you have suggested. As per back story I can suggest something like that:
"GLTF meshes consist of one or more primitives (You can read more here - https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes). If the mesh is represented as multiple primitives, this will result in multiple trimesh objects - one per each primitive. If the trimesh object originated from multi-primitive GLTF mesh you can use, then `trimesh.metadata['from_gltf_primitive']` will be True, otherwise False."
However, I'm not sure where in the docs this is supposed to go. Also the automated tests fail and I'm not entirely sure why.

**Comment by mikedh** [comment]
Awesome thanks for the changes! Don't worry about builds, they were broken upstream and I'm hoping they will be fixed by https://github.com/fredrik-johansson/mpmath/issues/580 although if they're not fixed in the next few days I'll remove the sympy install in python 2.

**Comment by ibozhilov** [comment]
Great! I'm not sure what is your release cycle, but would it be possible to make a release with the new field, once you merge the PR. Thanks in advance!

**Pull request merged**
