### PR TITLE
Allow showing of trimesh.Trimesh subclasses.

### PR DESCRIPTION
**Pull request by Marviel**
I've developed some subclasses of Trimesh that were not able to be shown without the changes of this commit.

### CODE REVIEW

**Comment by Marviel** [comment]
I can (and probably should...) write a test for this...

**Comment by mikedh** [comment]
Cool, thanks. Yeah just checking the class name is kind of sloppy, it was in there to avoid the circular import from trimesh.base and using isinstance.

**Comment by mikedh** [comment]
I moved your block into a function to replace other instances of this bug in https://github.com/mikedh/trimesh/commit/f49e428c6251e3da20ebc6e676d405023e313fb0 , let me know if that breaks anything for you.

**Comment by Marviel** [comment]
@mikedh hey thanks man! This library is awesome!

**Pull request merged**
