### PR TITLE
Add test and fix for preserving colors when adding point clouds

### PR DESCRIPTION
**Pull request by clemense**
This fixes the problem with:
```
pc1 = trimesh.PointCloud(np.random.rand(10, 3), colors=[[255, 0, 0, 255]] * 10)
pc2 = trimesh.PointCloud(np.random.rand(10, 3), colors=[[0, 255, 0, 255]] * 10)
(pc1 + pc2).show()   # this currently won't show any colored point clouds
```

### CODE REVIEW

**Comment by clemense** [comment]
One question: how do I ensure that my code is compliant with the repo's formatting rules? Is this there something more memorable than this?
```
autopep8 --recursive --aggressive --in-place --exit-code trimesh/
autopep8 --recursive --aggressive --in-place --exit-code tests/
```
Or maybe this could be documented in a `Contribute.md` ?

**Comment by mikedh** [comment]
```
autopep8 --recursive --aggressive --in-place --exit-code trimesh/
autopep8 --recursive --aggressive --in-place --exit-code tests/
```

Yeah that's exactly what I run haha I have it aliased to `ap`. Would it be helpful if I added it as `python setup.py format` or something?

**Comment by clemense** [comment]
Yes, I think that could be helpful but even more importantly having it documented somewhere. I found the above command by searching for the phrase "formatting" in the repository. So whether it is `python setup.py format` or `autopep8 --recursive --aggressive --in-place --exit-code trimesh/` I will search again for it in a few months, so finding it easily is my main concern.

**Comment by mikedh** [comment]
Sounds good, I added a quick contributing guide in `docs` for the next release feel free to edit/PR to: https://github.com/mikedh/trimesh/blob/27f250a25a5825e38c27d5027e03be1a28a692a0/docs/contributing.md

**Pull request merged**
