### PR TITLE
Handle coplanar points in oriented_bounds

### PR DESCRIPTION
**Pull request by pchorak**
A potential solution to issue https://github.com/mikedh/trimesh/issues/1848

These changes check for this specific issue in `oriented_bounds` by catching Qhull errors and confirming that the points are all co-planar (rank 2). If this is the case, the bounds are computed with a dedicated function that transforms the points onto the xy plane and then uses `oriented_bounds_2D` to find the bounds.

This solution feels a little excessive, so I would be very much open to suggestion. The Qhull error could also be avoided by adding `QJ` to the `qhull_options` of `trimesh.convex.convex.hull`, but I'm not sure we want to joggle points by default.

### CODE REVIEW

**Comment by mikedh** [comment]
This looks great thanks for the PR! I'll try to run and merge next week, my initial thoughts:

- I've actually been thinking about whether we should be storing `_convex_hull_raw` for meshes with just the raw output from `spatial.ConvexHull` because `oriented_bounds` doesn't need the face winding or normals to be consistant and repairing it is expensive. With recent speedups repairing the convex hulls is like 30% of `oriented_bounds` [benchmarked using this gist](https://gist.github.com/mikedh/e8043836b72931202b23ff183365b576).
- I like the catching `QHullError`!
- I'd probably move the coplanar case inside of `oriented_bounds` or rename it with a `_` prefix as end users should probably never be calling it?
- Are there major downsides to `QJ`? Open to adding it to the default args. The description seems pretty reasonable. I wasn't quite clear if it joggles it only when a precision issue occurs, or always:
> Option 'QJ' or 'QJn' joggles each input coordinate by adding a random number in the range [-n,n]. If a precision error occurs, It tries again. If precision errors still occur, Qhull increases n ten-fold and tries again. The maximum value for increasing n is 0.01 times the maximum width of the input. Option 'QJ' selects a default value for n. The header file [user_r.h](http://www.qhull.org/src/libqhull_r/user_.h#JOGGLEdefault) defines these parameters and a maximum number of retries. See [Merged facets or joggled input](http://www.qhull.org/html/qh-impre.htm#joggle).

**Comment by pchorak** [comment]
Adding `_convex_hull_raw` sounds like a nice speedup. I took a stab at this [here](https://github.com/mikedh/trimesh/commit/ff906cadb4c0e005fece566596ec431e67343292), but something went wrong because that version is running way slower. It looks like `oriented_bounds` uses the normals, such as [here](https://github.com/mikedh/trimesh/blob/main/trimesh/bounds.py#L198) where if they are not repaired there end up being many more edges.

Moving the coplanar case inside `oriented_bounds` sounds good; I've made that change.

I don't think there are _major_ downsides to `QJ`. The description made it sound like it always joggles inputs, although in some quick testing, the results seem exact even with `QJ`. My only concern was that, since I don't know how people are using trimesh, there might be use cases where someone needs accuracy to more than 7 significant digits and joggling could affect it.

**Comment by mikedh** [comment]
> Adding _convex_hull_raw sounds like a nice speedup. I took a stab at this [here](https://github.com/mikedh/trimesh/commit/ff906cadb4c0e005fece566596ec431e67343292), but something went wrong because that version is running way slower. It looks like oriented_bounds uses the normals, such as [here](https://github.com/mikedh/trimesh/blob/main/trimesh/bounds.py#L198) where if they are not repaired there end up being many more edges.

Oh that's a great point, computing normals is often surprisingly expensive and definitively not the sort of thing you want to be doing twice haha, I'll play with this as well.

> I don't think there are major downsides to QJ. The description made it sound like it always joggles inputs, although in some quick testing, the results seem exact even with QJ. My only concern was that, since I don't know how people are using trimesh, there might be use cases where someone needs accuracy to more than 7 significant digits and joggling could affect it.

Oh nice. Yeah have to think about it, 7 significant digits is pretty close to what the default `tol.merge` is, and having `convex_hull` work in more edge cases seems like a pretty reasonable tradeoff.

**Comment by mikedh** [comment]
Thanks for the fix and followups!

**Pull request merged**
