### PR TITLE
Adding solver_options and self_intersection to bool.intersection

### PR DESCRIPTION
**Pull request by Erkhembayaar**
image
Adding Solver Option and Use_Self making bool.intersection work in most cases

### CODE REVIEW

**Comment by mikedh** [comment]
Thanks for the PR! Since `solver` has only two options, maybe we should make both arguments booleans? I.e.: `use_self: bool = True, use_exact: bool = True`

As a side note, have you tried using the `pip install manifold3d` engine?

**Comment by Erkhembayaar** [comment]
Here is the new PR

**Comment by Erkhembayaar** [comment]
New commit with description - condition check to cond is True and removed some trailing whitespaces

**Comment by Erkhembayaar** [comment]
@mikedh Could you please review the pull request and inform me if there are any elements that need further attention or improvement?

**Pull request merged**
