### PR TITLE
Add collada I/O

### PR DESCRIPTION
**Pull request by mmatl**
This does better COLLADA I/O w/ support for materials and such. Still need to do proper texture exporting, but can add that later. One quirk of this is that `TextureVisuals` should have its `uv` attribute be optional, as sometimes it's useful to specify a material without any texture (i.e. can still specify emission, metalness, roughness, etc...).

This relies on `pycollada`, which, as far as I can tell, only depends on `lxml` and optionally `pillow`.

### CODE REVIEW

**Comment by mikedh** [comment]
Nice! `pycollada` looks a heck of a lot better than `pyassimp`, this looks good to me. I did notice that it looks like the latest version on pypi renamed `.img` to `.image`, which once I changed this worked great (I couldn't figure out how to push to the PR but feel free to take anything from https://github.com/mikedh/trimesh/commit/2f9ddd4edf3cc29f4819d8c36b2ef0a656fabbd9)

On some slightly janky test files I had lying around, I saw a lot of `DaeSomethingException` (I forget the exact one) when trying to load images, where it couldn't locate the files due to a resolver issue. I think the only thing for those is to wrap them. 

Also yeah I agree with making UV's optional.

**Comment by mmatl** [comment]
Hi Mike! New code pushed just now:

- Integrated the changes you asked for in that link.
- Added code to handle resolving textures when loading from colladas.
- Also (EXCITING) -- figured out a relatively clean way to prevent textures from looking bad at the seams of objects. Basically, when merging vertices, you only merge vertices whose positions AND uv coordinates are identical. Then, you forcibly re-compute vertex normals and merge to the normal after grouping vertices by position. I included this change as well -- could probably go in its own PR, but can move it later if you want.

Still need to handle texture exports, although I do see a reasonable path forward for that I think (pass a resovler to the exporter, try to get a filename from PIL images, and export to a reasonable location).

Best,
Matt

**Comment by mikedh** [comment]
Awesome! I’ve been working on a branch (`feature/scene`) to try to make the Scene objects slightly nicer.  I think it’d be cool if you could load a scene containing lights and cameras via collada/assimp/gltf/etc and send it straight to `pyrender` or any other endpoint (notebooks/yafaray/etc) and have it do something reasonable. 

My short list of things to make this happen (let me know if I missed anything):
- Add light objects to trimesh that can be used by any endpoints (also resolves #193). Your light model in pyrender looked great so I yoinked it, though I removed some of the rendering specific items (shadow), hopefully this is OK with you. 
- Every scene has a single camera object, `set_camera` creates it if it isn’t passed.
- Every scene has a list of lights and an “auto light” function if nothing is set that does something reasonable.

I’ll merge into the feature branch and try to get this released sometime this week. Thanks for the PR!

**Comment by mmatl** [comment]
@mikedh Sounds awesome! And I'm totally up for that, since COLLADA and GLTF natually support scene graphs + cameras + lights and such. Happy to help with getting that feature branch done, let me know if there's anything I can do to help.

**Pull request merged**
