### PR TITLE
Filter invalid kwargs for Trimesh and ColorVisuals

### LINKED ISSUE #275: unused kwargs in trimesh.base.Trimesh
Why trimesh does not check unused kwargs passed to trimesh.Trimesh?
I had difficulty while debugging because of typo of kwargs: (x) preprocess (o) process.

### PR DESCRIPTION
**Pull request by wkentaro**
Close #275

### CODE REVIEW

**Comment by mikedh** [comment]
Thanks for the PR! Maybe we should just remove `kwargs` entirely from the constructor and add a `visual=None`, rather than filtering if we're going to raise anyway if anything is passed.

**Comment by wkentaro** [comment]
Updated.

**Comment by mikedh** [comment]
LGTM- thanks for the PR!

**Comment by wkentaro** [comment]
Ok, I see.

**Pull request merged**
