### PR TITLE
prevent division by zero

### PR DESCRIPTION
**Pull request by YuanWenqing**
Example (Assets: [ray.zip](https://github.com/mikedh/trimesh/files/12449626/ray.zip)) :
~~~python
import numpy as np
import trimesh
from trimesh.ray import ray_triangle

ray_origins = np.load('ray.origins.npy')
ray_directions = np.load('ray.directions.npy')
mesh = trimesh.load('ray.mesh.obj')
print(mesh.is_watertight) # True

intersector = ray_triangle.RayMeshIntersector(mesh)
intersector.intersects_location(ray_origins,ray_directions)
~~~

Produce Error:
~~~python
.../trimesh/ray/ray_triangle.py:398: RuntimeWarning: divide by zero encountered in true_divide
  t = (axis_bound - axis_ori) / axis_dir
.../trimesh/ray/ray_triangle.py:410: RuntimeWarning: invalid value encountered in multiply
  on_a = (ray_directions * t_a) + ray_origins
~~~
And leading to
~~~python
.../trimesh/ray/ray_triangle.py in intersects_location(self, ray_origins, ray_directions, **kwargs)
    105              ray_directions=ray_directions,
    106              return_locations=True,
--> 107              **kwargs)
    108         return locations, index_ray, index_tri
    109 

.../trimesh/ray/ray_triangle.py in intersects_id(self, ray_origins, ray_directions, return_locations, multiple_hits, **kwargs)
     64              tree=self.mesh.triangles_tree,
     65              multiple_hits=multiple_hits,
---> 66              triangles_normal=self.mesh.face_normals)
     67         if return_locations:
     68             if len(index_tri) == 0:

.../trimesh/ray/ray_triangle.py in ray_triangle_id(triangles, ray_origins, ray_directions, triangles_normal, tree, multiple_hits)
    238         ray_origins=ray_origins,
    239         ray_directions=ray_directions,
--> 240         tree=tree)
    241 
    242     # get subsets which are corresponding rays and triangles

.../trimesh/ray/ray_triangle.py in ray_triangle_candidates(ray_origins, ray_directions, tree)
    347 
    348     for i, bounds in enumerate(ray_bounding):
--> 349         ray_candidates[i] = np.array(list(tree.intersection(bounds)),
    350                                      dtype=np.int64)
    351         ray_id[i] = np.ones(len(ray_candidates[i]), dtype=np.int64) * i

.../rtree/index.py in intersection(self, coordinates, objects)
    819             return self._intersection_obj(coordinates, objects)
    820 
--> 821         p_mins, p_maxs = self.get_coordinate_pointers(coordinates)
    822 
    823         p_num_results = ctypes.c_uint64(0)

.../rtree/index.py in get_coordinate_pointers(self, coordinates)
    368             if not coordinates[i] <= coordinates[i + dimension]:
    369                 raise RTreeError(
--> 370                     "Coordinates must not have minimums more than maximums"
    371                 )
    372 

RTreeError: Coordinates must not have minimums more than maximums
~~~

### CODE REVIEW

**Comment by mikedh** [comment]
Thanks for the fix!! Quick notes

- `1 / tol.zero` seems like it produces pretty arbitrary large results... if it's a denominator would making it `np.inf` make sense, which would set returned values to zero? You could also do this with a mask `nonzero = a != 0.0` and then use advanced indexing on the divide.
- could you add a quick test?

```
In [19]: a  = np.ones(10, dtype=np.float64)

In [21]: a[0] = np.inf

In [22]: a[1] = trimesh.constants.tol.zero

In [23]: 1.0 / a
Out[23]:
array([0.e+00, 1.e+13, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e+00,
       1.e+00, 1.e+00])
```

**Comment by YuanWenqing** [comment]
Thanks for the note!
Previously I was not familiar with the algorithm, thus I just added the very "direction" correction.

**Comment by mikedh** [comment]
Thanks for the fix!!

**Comment by YuanWenqing** [comment]
@mikedh Could you release a hotfix version including this PR recently? By fine-tuning some args, this issue was bypassed, but it appears again now. This PR is really necessary for me.

**Pull request merged**
