### PR TITLE
Run style check on CI

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/mikedh/trimesh/issues/390

- Now we run only for trimesh/ (to gradually introduce).

### CODE REVIEW

**Comment by mikedh** [comment]
Nice, looks terrific thanks! Only though is maybe we should run just `flake8` in CI? `autopep8` is more of a formatter than a linter.

**Comment by wkentaro** [comment]
If you use `autopep8 --in-place`, I think it's worth to add `autopep8` to CI, because it always makes sure that there is no diff after running `autopep8`.
If you use `autopep8` as an information teller and manually change ignoring some of the warnings, I think we should remove `autopep8` from CI.

**Comment by wkentaro** [comment]
Actually, I've learned this strategy from Chainer (a deep learning library):
https://github.com/chainer/chainer/blob/0fd15073532496ed495b9318c4fece4e077ce15f/scripts/ci/steps.sh#L104

Also I guess `--exit-code` is designed for this usage.

**Comment by mikedh** [comment]
Oh nice, `--exit-code` looks good. Thanks for the PR!

**Pull request merged**
