### PR TITLE
Pass through node extension data from gltfs

### PR DESCRIPTION
**Pull request by pchorak**
It would be great to pass through any node extension data from gltf files. Putting the extension data in `extras` seems simplest since the field appears unused for gltfs (it looks like the actual extras are put in `metadata`, is this intended?) but is [passed on when constructing the graph](https://github.com/mikedh/trimesh/blob/main/trimesh/scene/transforms.py#L75).

### CODE REVIEW

**Comment by mikedh** [comment]
Awesome thanks! Yeah the `scene.metadata` == `gltf.extras` is a little wonky, but it is nice because it preserves `scene.metadata` through a GLTF round-trip. 

Agreed it would be nice to preserve `extensions` and ideally it might even round-trip through gltf->trimesh->gltf. My only hangup is that the (`extensions == extras, extras == metadata`) mapping is already confusing me haha. 

I also don't totally recall where the `kwargs['extras']` end up, but I don't see them in the `trimesh.Scene` constructor or in `trimesh.exchange.load.load_kwargs`? One option is we could map `extensions` to `Scene.metadata['extensions']` (although then we have to worry about if there is an extra named extensions :).

**Comment by pchorak** [comment]
Thanks for the review and thoughts! I'll take a look again and try to see where might be good to put 'extensions'. `Scene.metadata` would also be convenient, but you raise a good point about potential issues if there's an extra with that name.

**Comment by pchorak** [comment]
The scene and mesh extras are making it into the scene and geometry metadata and through round-trips saving/loading .gltf files. However, it looks like the node extras [here](https://github.com/mikedh/trimesh/blob/main/trimesh/exchange/gltf.py#L1642) are not making it into the scene graph and thus through round-trips (lost when loading). I augmented one of the unit tests to fail because of this in 073ab83. I fixed the round-trip by putting the node extras in "extras" in 9c3858b, so that when the node `kwargs` are passed to `SceneGraph.update` by [handle_scene](https://github.com/mikedh/trimesh/blob/main/trimesh/exchange/load.py#L431), the extras are preserved by [this]([](https://github.com/mikedh/trimesh/blob/main/trimesh/scene/transforms.py#L76)) existing code.

Lastly, I added some new arguments and code to handle node `extensions` in a similar way to node `extras`.

**Comment by pchorak** [comment]
Hi! Any thoughts/input on the current version of this? It should allow gltf _node_ extras and extensions to be loaded and saved, neither of which are supported in the current version (not be confused with the _scene_ and _mesh_ extras, which are supported in the current version via metadata).

**Comment by pchorak** [comment]
I like the idea of unifying everything in metadata and made changes to do this. The node/edge metadata are still handled a little differently; since the edge data is a dictionary, the metadata are an item in the dictionary instead of an object attribute. I did change the key from 'extras' to 'metadata', and also changed the last argument of `Scene.add_geometry` accordingly.

**Comment by mikedh** [comment]
Awesome thanks for the fixes!! Yeah having it as an item in the dictionary makes total sense. It's also super nice to round-trip extensions. I'll merge and then release in #1870

**Comment by mikedh** [comment]
Any thoughts on putting extension in `scenes[0]` vs the root of the file as proposed in #1973?

**Comment by pchorak** [comment]
Thanks for pinging me! I replied with some input in the new PR but am ok either way.

**Pull request merged**
