### PR TITLE
WIP: Properly support Big Endian arches when loading binary meshes

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by hroncok** [comment]
Will fix https://github.com/mikedh/trimesh/issues/249 but still need more changes.

**Comment by mikedh** [comment]
Looks great, thanks! I'm happy to merge this whenever, just let me know when you're ready.

**Comment by mikedh** [comment]
I'm going to merge as it seems like a standalone improvement and we can address additional BE problems via another PR. Thanks for the fix!

**Comment by hroncok** [comment]
OK. I'm not sure if/when I'll get to the rest of it :(

**Pull request merged**
