### PR TITLE
calculate integral mean curvature

### PR DESCRIPTION
**Pull request by keisuke-ishihara**
This function calculates the integral mean curvature of a mesh. With this addition, all four Minkowski functionals for a surface mesh embedded in 3d can be calculated by Trimesh. (Volume, Area, Integral Mean Curvature, Euler number)

In the most general case, the lengths of the two numpy arrays,
self.face_adjacency_angles
and
self.edges_unique_length,

may not be equal. This could be checked with an 'assert', if necessary.

### CODE REVIEW

**Comment by mikedh** [comment]
Nice idea thanks for the PR! Is there a paper somewhere that has reference values for some common primitives (sphere, box, capsule) we could check for a unit test?

So `edges_unique` isn't necessarily going to correspond to the `face_adjacency` indexing scheme, I think the lengths need to be recalculated from `face_adjacency_edges`. This can probably be done more gracefully but for now I think this  replicates your logic with the realigned indexing:

```
In [28]: edges_length = np.linalg.norm(np.subtract(*m.vertices[m.face_adjacency_edges.T]), axis=1)

In [30]: edges_length
Out[30]: 
array([1.        , 1.        , 1.41421356, 1.        , 1.        ,
       1.        , 1.41421356, 1.41421356, 1.        , 1.        ,
       1.        , 1.        , 1.41421356, 1.41421356, 1.41421356,
       1.        , 1.        , 1.        ])

In [31]: m.face_adjacency_angles
Out[31]: 
array([1.57079633, 1.57079633, 0.        , 1.57079633, 1.57079633,
       1.57079633, 0.        , 0.        , 1.57079633, 1.57079633,
       1.57079633, 1.57079633, 0.        , 0.        , 0.        ,
       1.57079633, 1.57079633, 1.57079633])

In [32]: m.face_adjacency_angles * edges_length
Out[32]: 
array([1.57079633, 1.57079633, 0.        , 1.57079633, 1.57079633,
       1.57079633, 0.        , 0.        , 1.57079633, 1.57079633,
       1.57079633, 1.57079633, 0.        , 0.        , 0.        ,
       1.57079633, 1.57079633, 1.57079633])

In [33]: (m.face_adjacency_angles * edges_length).sum() * 0.5
Out[33]: 9.42477796076938

```

**Comment by keisuke-ishihara** [comment]
Thanks for the suggestion of using face_adjacency to obtain the edge lengths!

Some background of integral mean curvature can be found in slide 44-56 in [this lecture note (pdf)](https://brickisland.net/DDGFall2017/wp-content/uploads/2017/11/CMU_DDG_Fall2017_10_DiscreteCurvature.pdf).

I've derived the integral mean curvature (IMC) for the common primitives:

For a sphere of radius R:
IMC = (mean curvature) * (area) = 1/R * 4* pi *R^2 = 4* pi *R

For a capsule defined as the cylinder of radius R and length L with its two ends decorated by a hemispherical cap of radius R:
IMC = (IMC of cylinder) + (IMC of two hemispheres)
= 1/2R * 2* pi *R*L + 4* pi *R = pi*L + 4 * pi * R
note: L should be equivalent to the height parameter for the 'capsule' function in  trimesh/creation.py

For a box defined by length L, width W, height H, we use the discrete definition:
IMC = sum(edge lengths * angles) * 0.5 = 4*(L+W+H) * pi/4 * 0.5 = (L+W+H)*pi/2 

Let me know where I could implement the unit test. If you could point to a good example (e.g. volume and area of common primitives) that I can follow, that would be nice.

**Comment by mikedh** [comment]
Awesome unit test looks great, thanks for deriving the analytical equivalents!

**Comment by keisuke-ishihara** [comment]
Thanks for the feedback! This was my first time contributing to a software package with a PR. I learned about unit tests and the tools for PEP8 formatting, and it was fun.

**Comment by mikedh** [comment]
Thanks for the contribution, it's much appreciated! Glad contributing wasn't too painful!

**Pull request merged**
