### PR TITLE
Add trimesh.scene.camera.Camera to set camera parameters

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/mikedh/trimesh/issues/253

This only supports some parameters in camera intrinsic matrix.

### CODE REVIEW

**Comment by wkentaro** [comment]
## Example

You need #255 

```python
#!/usr/bin/env python

import numpy as np
import trimesh
import trimesh.transformations as tf


trimesh.util.attach_to_log(level='WARNING')


def get_homography_rpy(roll, pitch, yaw, distance, center):
    translation = tf.translation_matrix(center)
    translation[2][3] += distance  # z from center
    rotation = (
        tf.rotation_matrix(roll, [1, 0, 0], point=center) @
        tf.rotation_matrix(pitch, [0, 1, 0], point=center) @
        tf.rotation_matrix(yaw, [0, 0, 1], point=center)
    )
    transform = translation @ rotation
    return transform


if __name__ == '__main__':
    extents = (0.5, 0.5, 0.5)
    box = trimesh.creation.box(extents)
    box.visual.face_colors = [255, 0, 0, 127]

    scene = trimesh.Scene()
    scene.add_geometry(box, node_name='box')

    scene.add_geometry(trimesh.creation.axis(np.eye(4)))

    roll, pitch, yaw = 0, 0, np.deg2rad(45)
    distance = 0.9
    center = (0, 0, 0)
    transform = get_homography_rpy(roll, pitch, yaw, distance, center)
    print('Using RPY (Red)')
    print('Distance:', distance)
    print('RPY:', (roll, pitch, yaw))
    print(transform)
    scene.add_geometry(
        trimesh.creation.axis(transform, origin_color=(255, 0, 0))
    )

    # Camera for SceneNet RGB-D
    camera = trimesh.scene.Camera(
        width=320,
        height=240,
        fovx=60,
        fovy=45,
        matrix=transform
    )
    scene.set_camera(camera=camera)

    # scene.graph.update(
    #     frame_from='camera',
    #     frame_to=scene.graph.base_frame,
    #     matrix=transform,
    #     geometry='camera',
    # )

    # scene.show()

    import io
    import PIL.Image
    with io.BytesIO() as f:
        f.write(scene.save_image((camera.width, camera.height)))
        PIL.Image.open(f).save('result.png')
```

**Comment by mikedh** [comment]
Awesome looks great! Couple minor thoughts:

- Could you replace fx/fy with a (2,) float array and fovx/fovy with (2,) float array?  `width`/`height` could be combined into a `resolution` parameter
- How about a simple unit test which specifies parameters in varies ways then asserts K is close to ground truth?
- Could you add a docstring to `Camera.__init__` describing what the parameters do?

**Comment by wkentaro** [comment]
I'm not sure what is the right name for 'fx/fy' and 'fovx/fovy'.
Currently, I'm using `fxfy` and `fovxy`.

**Comment by wkentaro** [comment]
I think I addressed all comments.

**Pull request merged**
