### PR TITLE
URDF bug fix + path extrusion

### PR DESCRIPTION
**Pull request by mmatl**
The big contribution here is 3D path extrusion -- just specify a polygon and a path, and you can extrude the polygon in arbitrary 3D space. For example, I created this spring with the new function:

image

Up for any edits for efficiency :)

### CODE REVIEW

**Comment by mmatl** [comment]
Hold up on this for just a sec, want to finish checking for bugs.

**Comment by mikedh** [comment]
Whoa this looks sweet! Roger on holding off for a minute. 

Want to add a simple integration test to test_creation? Maybe just the code that generated that helix with an `assert mesh.is_volume` at the end or something? Though now that I'm thinking about it I don't remember if meshpy gets installed for the travis build... I'll look in to that.

**Comment by mmatl** [comment]
Okay, fixed the bug (just was forgetting to unitize some vectors, which caused problems when small vertices were used).

I'll add that integration test now, and we can comment it out if meshpy isn't installed on Travis.

**Comment by mmatl** [comment]
Added the integration test -- let me know if it causes issues w/ travis, and I can have it return early (I'll leave the code around as an example).

**Comment by mikedh** [comment]
Cool- I'll merge into devel and fix the meshpy travis thing- thanks!

**Comment by mikedh** [comment]
I added an exit if there's no meshpy, I'll merge into master as soon as [that build succeeds.](https://travis-ci.org/mikedh/trimesh/builds/344554029)

Oh one other thing- this operation is called a "sweep" in [some CAD packages](http://help.solidworks.com/2016/english/solidworks/sldworks/t_creating_a_sweep.htm)- mind if I rename the function to `sweep_polygon`?

**Comment by mmatl** [comment]
Not at all, that works perfectly for me haha :)

**Pull request merged**
