### PR TITLE
Show camera as mesh

### PR DESCRIPTION
**Pull request by wkentaro**
```python
#!/usr/bin/env python

import numpy as np
import trimesh
import trimesh.transformations as tf


trimesh.util.attach_to_log(level='WARNING')


def get_homography_rpy(roll, pitch, yaw, distance, center):
    translation = tf.translation_matrix(center)
    translation[2][3] += distance  # z from center
    rotation = (
        tf.rotation_matrix(roll, [1, 0, 0], point=center) @
        tf.rotation_matrix(pitch, [0, 1, 0], point=center) @
        tf.rotation_matrix(yaw, [0, 0, 1], point=center)
    )
    transform = translation @ rotation
    return transform


def get_homography_lookat(eye, lookat):
    # both are positions
    assert len(eye) == 3
    assert len(lookat) == 3


if __name__ == '__main__':
    extents = (0.5, 0.5, 0.5)
    box = trimesh.creation.box(extents)
    box.visual.face_colors = [255, 0, 0, 127]

    scene = trimesh.Scene()
    scene.add_geometry(box, node_name='box')

    scene.add_geometry(trimesh.creation.axis())

    roll, pitch, yaw = 0, 0, np.deg2rad(45)
    distance = 0.9
    center = (0, 0, 0)
    transform = get_homography_rpy(roll, pitch, yaw, distance, center)
    print('Using RPY (Red)')
    print('Distance:', distance)
    print('RPY:', (roll, pitch, yaw))

    scene_camera = scene.copy()
    camera = trimesh.scene.Camera(
        resolution=(320, 240),
        fov=(60, 45),
        transform=transform
    )
    scene_camera.set_camera(camera=camera)
    scene_camera.show(start_loop=False)

    # this transform is necessary to get correct image
    transform = transform @ tf.rotation_matrix(np.deg2rad(-180), [1, 0, 0])
    camera.transform = transform
    scene.add_geometry(camera.as_meshes())
    scene.show()
```

screen shot 2018-11-26 at 22 54 44

### CODE REVIEW

**Comment by wkentaro** [comment]
```
transform = transform @ tf.rotation_matrix(np.deg2rad(-180), [1, 0, 0])
```

Actually this is necessary because z axis is other way around in trimesh.

**Comment by mikedh** [comment]
Nice! I think this probably makes most sense in`trimesh.creation`, as `camera_marker` or something:

```
def camera_marker(camera, marker_height):
    """
    Create a visual marker for a camera object, including an axis marker and FOV indicator. 

    Parameters
    ---------------
    camera : trimesh.scene.Camera
        Camera object with FOV and transform defined
    marker_height : float
        How far along the camera Z should FOV indicators be
 
    Returns
    ------------
    meshes : list
       Contains Trimesh and Path3D objects which can be visualized
    """
```


- imports should probably be relative (i.e. `from .path import load_path`)
- could you add a docstring?
- I think focal_length is a little overloaded; I changed it to "marker_height" or something. Probably also want to make origin radius always relative to this. 
- Is the PointCloud necessary? I don't see them in your screenshot.

**Comment by wkentaro** [comment]
Updated example:

```python
#!/usr/bin/env python

import numpy as np
import trimesh
import trimesh.transformations as tf


trimesh.util.attach_to_log(level='WARNING')


def get_homography_rpy(roll, pitch, yaw, distance, center):
    translation = tf.translation_matrix(center)
    translation[2][3] += distance  # z from center
    rotation = (
        tf.rotation_matrix(roll, [1, 0, 0], point=center) @
        tf.rotation_matrix(pitch, [0, 1, 0], point=center) @
        tf.rotation_matrix(yaw, [0, 0, 1], point=center)
    )
    transform = translation @ rotation
    return transform


def get_homography_lookat(eye, lookat):
    # both are positions
    assert len(eye) == 3
    assert len(lookat) == 3


if __name__ == '__main__':
    extents = (0.5, 0.5, 0.5)
    box = trimesh.creation.box(extents)
    box.visual.face_colors = [255, 0, 0, 127]

    scene = trimesh.Scene()
    scene.add_geometry(box, node_name='box')

    scene.add_geometry(trimesh.creation.axis())

    roll, pitch, yaw = 0, 0, np.deg2rad(45)
    distance = 0.9
    center = (0, 0, 0)
    transform = get_homography_rpy(roll, pitch, yaw, distance, center)
    print('Using RPY (Red)')
    print('Distance:', distance)
    print('RPY:', (roll, pitch, yaw))

    scene_camera = scene.copy()
    camera = trimesh.scene.Camera(
        resolution=(320, 240),
        fov=(60, 45),
        transform=transform
    )
    scene_camera.set_camera(camera=camera)
    scene_camera.show(start_loop=False)

    # this transform is necessary to get correct image
    transform = transform @ tf.rotation_matrix(np.deg2rad(-180), [1, 0, 0])
    camera.transform = transform
    mesh = trimesh.creation.camera_marker(camera=camera)
    scene.add_geometry(mesh)
    scene.show()

```

**Comment by wkentaro** [comment]
I addressed all of your comments. Could you review again?

**Comment by mikedh** [comment]
Awesome! Merged to master in https://github.com/mikedh/trimesh/commit/ef90ebc8fd55cc1161669c266191a023a9c1eb12 and should release as soon as the build finishes.  

I made some minor changes, the main thing was moving the import into the function and a `try/except ImportError` block to keep path a soft dependency.  I also changed the `load_path` to a single call by stacking into one array of line segments.

Thanks for the PR's!! It's great to get your work into the master branch and releases :smile:

**Comment by wkentaro** [comment]
Thanks for your help!

**Pull request merged**
