### PR TITLE
Scenery: Lights and Cameras

### LINKED ISSUE #193: Set light in a scene
Hi,
Is it possible to set the light in a scene?
(I would like to visualize colored point clouds whose colors are not affected by the perspective of the camera; right now colors change drastically when rotating the point cloud in the viewer)
Thanks!

### PR DESCRIPTION
**Pull request by mikedh**
Previously, our support for cameras was limited and lights nonexistent. This is a followup to #281 which added texture support. The thought here is that it would be cool to load a scene file (DAE/GLTF/assimp) including lights and cameras, and then pass it to a render or export endpoint (pyrender, GLTF, notebooks, pyglet, yafaray, etc) and have light/camera information preserved. 

The basic change is that now scenes always have a SINGLE camera object `scene.camera` which can be specified manually or is autogenerated if not. Scenes have a LIST of light objects `scene.lights` which can be set, or is automatically generated to look "OK" otherwise.  

`scene.graph` is still pretty rough and probably the worst part about scene objects. I like having a single graph object based on networkx, but this could do with one (or several) API/cleanup passes that are out of scope of this PR. 

This is working towards #301, and includes #317.  I'm very open to suggestions haha- any puts @mmatl @wkentaro?

Changes:
- scene objects now have a single `scene.camera` object, which can be assigned or if unset will be autogenerated when requested
- scene objects now have a list of `scene.lights`, which `viewer.windowed` uses (fixes #193)
- `trimesh.scene.lighting` was pulled pretty much directly from `pyrender`. The only major change is renaming `range` to `radius` to avoid conflicting with the builtin function.
- `load_pyssimp` now returns scene objects. `pyassimp` is currently tough to install, I made some speedups and am working to get wheels including the correct version of the shared library building here https://github.com/mikedh/pyassimp 
- DAE now returns scenes. Tests are going to keep failing until https://github.com/pycollada/pycollada/pull/86 is merged or I remove `barrett-wam.zae` from models.

### CODE REVIEW

**Comment by mmatl** [comment]
Looking amazing! Will provide input when I get a change.

**Comment by mmatl** [comment]
@mikedh Anything in particular I can help with to get this finished up?

**Comment by mikedh** [comment]
Hey Matt, this should be mostly ready to go. Just checking if the "single camera, multiple lights" model works for you before merging. 

There's still some miscellaneous stuff that can probably be addressed in master or later. Some quick notes:

- colors in the rest of trimesh are RGBA `uint8`. I kind of regret not making these 0.0-1.0 floats, but I changed the `scene/lighting` colors to match the rest of trimesh for consistencies sake. OpenGL takes RGBA colors for lights... what does alpha even mean for lights :grin: 
- `scene/cameras/look_at` function seems right-ish, but I'd like to check it more carefully and unit test. Meshes appear to be more than filling up the window, rather than exactly filling up one axis of the window as intended. 
- `exchange/dae` has TODO placeholders for converting lights + cameras to the new data types

**Comment by mmatl** [comment]
Hi Mike,

Great work! Yeah, the single-camera, multiple-lights model works perfectly for me. I can't really think of cases where someone _really_ actually wants multiple cameras, and if they do, they can always just use pyrender directly to add them.

With regards to the other stuff:

- Yeah, `uint8` is more efficient, but all the OpenGL stuff uses `float32` for all colors :/ And yeah, I was SO confused about why lights have an alpha -- as far as I can tell, you _never_ use light alphas in shading...
- I'll look over `scene/cameras/look_at`.
- I can add those placeholders if you want, either here or in master.

**Comment by mikedh** [comment]
Sounds good! Yeah I'm open to converting all colors to float RGBA someday, though I think it would be important to do it everywhere rather than mixing color data types. 

If you wouldn't mind taking a look at (hah) `look_at` and the DAE light/camera conversions that would be awesome thanks!

Brief punch list for visual stuff, in no order and with no particular timeline:
- DAE light+camera conversion
- `look_at` test and fixes
- export `camera.transform` to GLTF (#237) and update notebook viewer to use it
- export lights to GLTF
- export texture to GLTF

**Comment by mmatl** [comment]
It seems to me like you should transform the points _into_ the camera's space (i.e. the inverse of the initial camera rotation), do your calculations there, and then transform the camera center back to the world space?

Here's my re-implementation:

```python
def look_at(points, fov, rotation=None):
    """
    Generate transform for a camera to keep a list
    of points in the camera's field of view.
    Parameters
    -------------
    points : (n, 3) float
      Points in space
    fov : (2,) float
      Field of view, in DEGREES
    rotation : None, or (4, 4) float
      Rotation matrix for initial rotation

    Returns
    --------------
    transform : (4, 4) float
      Transformation matrix with points in view
    """
    if rotation is None:
        rotation = np.eye(4)
    else:
        rotation = np.asanyarray(rotation, dtype=np.float64)
    points = np.asanyarray(points, dtype=np.float64)

    # Transform points to camera frame (just use the rotation part)
    rinv = rotation[:3, :3].T
    points_c = rinv.dot(points.T).T

    # Find the center of the points' AABB in camera frame
    center_c = points_c.min(axis=0) + 0.5 * points_c.ptp(axis=0)

    # Re-center the points around the camera-frame origin
    points_c -= center_c

    # Find the minimum distance for the camera from the origin
    # so that all points fit in the view frustrum
    tfov = np.tan(np.radians(fov) / 2.0)
    dist = np.max(np.abs(points_c[:, :2]) / tfov + points_c[:, 2][:, np.newaxis])

    # Set the pose translation by sending the 
    center_w = rotation[:3, :3].dot(center_c)
    cam_pose = rotation.copy()
    cam_pose[:3, 3] = center_w + dist * cam_pose[:3, 2]

    return cam_pose
```
The behavior is such that at least one edge of the screen is _juuuuust_ touching the object. The object won't necessarily touch both sides, as we're constrained to search along the view vector while keeping the object's AABB center in the middle of the scene. Getting the object to fill a full axis is quite a bit harder, I think.

Examples here:
fuze
ico
drill

**Pull request merged**
