### PR TITLE
Feature/added ctm support

### PR DESCRIPTION
**Pull request by lejafar**
I haven't really been able to fully test it, but I thought I would first get some feedback before going further

### CODE REVIEW

**Comment by mikedh** [comment]
Looks great! That was fast hahah. Since its a ctypes thing that doesn't require building I think this could work nicely, as long as we keep it as a soft dependency by wrapping any import exceptions. 

The one thing that people are guaranteed to raise issues with is how to get the right shared library. 

Options:
- Set up an upstream python package that bundles the shared library (like we did with [python-fcl](https://github.com/BerkeleyAutomation/python-fcl)) by building it with cibuildwheel, that we can add to the `trimesh` dependency list. 
- (easier) Just add a shell script we can point people at, like the [draco one](https://github.com/mikedh/trimesh/blob/master/docker/builds/draco.bash).

**Comment by lejafar** [comment]
I prefer the second one! And I'll also write the export method!

**Comment by mikedh** [comment]
Cool! Just out of curiosity (still happy to merge), why OpenCTM over [Draco](https://github.com/google/draco)? OpenCTM looks basically abandoned on their Sourceforge and Github forks, while draco is quite active and backed by a large corporation.

**Comment by lejafar** [comment]
Its just that I'm receiving the files mostly in a OpenCTM format (I'm working in additive), we do use draco but just for creating previews though!

**Comment by mikedh** [comment]
Sounds good! Yeah if you add that shell script I'll merge. I may move the files around a little bit, I was thinking of making a directory `openctm` in io, and then do the try block in `__init__`:

```
try:
     from .ctm import load_ctm
     ctm_loaders = {'ctm': load_ctm}
except ImportError:
    ctm_loaders = {}
```

**Comment by mikedh** [comment]
Oh- would you mind also adding a small (500kb- ish) test model in the openCTM format to /models?

**Comment by lejafar** [comment]
I will get that done!

**Pull request merged**
