### PR TITLE
Add distance checking wrappers to collision mgr

### PR DESCRIPTION
**Pull request by mmatl**
This relies on python-fcl>=0.0.7 to work (there was a bug in 0.0.6
for distance checking specifically).

### CODE REVIEW

**Comment by mmatl** [comment]
Hi Mike! Just a quick update to add wrappers for more of python-fcl's functionality -- specifically, the distance checking code. Should work as advertised with python-fcl >= 0.0.7, which is on pypi now.

**Comment by mmatl** [comment]
Looks like the build failures were due to apt failing -- probably just a travis bug.

**Comment by mikedh** [comment]
This looks awesome, thanks! Yeah looks like travis is just being flaky- I restarted and will merge as soon as it finishes.

**Comment by mmatl** [comment]
Thanks :)

**Pull request merged**
