### PR TITLE
add draco support for gltf

### LINKED ISSUE #1971: [Bug] load and export with glb files
try using this model: https://modelviewer.dev/shared-assets/models/NeilArmstrong.glb
```
import trimesh
a = trimesh.load("NeilArmstrong.glb")
a.export("output.glb")
```
then we will get a glb model with wrong baseColorFactor. The source code treats the origin baseColorFactor as int values and normalize it using 255, then output wrong values.

### PR DESCRIPTION
**Pull request by seed93**
1. add draco support for gltf
2. fix #1971 

Note: only export_glb with draco supported, not for gltf export yet.

### CODE REVIEW

**Comment by seed93** [comment]
The failed format check is not introduced by this merge request.

**Comment by seed93** [comment]
rebase done

**Comment by mikedh** [comment]
Awesome thanks for the followup this looks a lot closer!!

- What's the maintenance plan for `pydracogltf`? Would you be interested in adding it to the `trimesh` github org?
- Where's the source for the [pydracogltf binary libraries](https://github.com/seed93/pydracogltf/tree/master/pydracogltf/libs)? Without the source it's hard to see what's happening and we can't add it as a dependency. 
- I'm happy to help setting up the CI for this, I would use this as a template: [embreex/pyproject.toml](https://github.com/mikedh/embreeX/blob/main/pyproject.toml)

**Comment by seed93** [comment]
> Awesome thanks for the followup this looks a lot closer!!
> 
>     * What's the maintenance plan for `pydracogltf`? Would you be interested in adding it to the `trimesh` github org?
> 
>     * Where's the source for the [pydracogltf binary libraries](https://github.com/seed93/pydracogltf/tree/master/pydracogltf/libs)? Without the source it's hard to see what's happening and we can't add it as a dependency.
> 
>     * I'm happy to help setting up the CI for this, I would use this as a template: [embreex/pyproject.toml](https://github.com/mikedh/embreeX/blob/main/pyproject.toml)

I can maintain this project and I am happy to add it to `trimesh` github org.
The source code of this binary is [here](https://github.com/ux3d/blender_extern_draco), used for blender.

**Comment by seed93** [comment]
Shall we merge this request?

**Comment by mikedh** [comment]
Thanks for the followup! I think the upstream project still needs a bit of work before we can add a dependency:
- the source code for the `libs` should be added to `pydracogltf`
- the compiled artifacts in [pydracogltf/libs](https://github.com/seed93/pydracogltf/tree/master/pydracogltf/libs) should be removed from the repo
- `pyproject.toml` should use cibuildwheel to compile the libraries from source, as  [in embreex/pyproject.toml](https://github.com/mikedh/embreeX/blob/891359d0858d86de09bf245744e5f09bb23eaf83/pyproject.toml)
- CI should release to PyPi using a token stored in the repo's secrets.

**Comment by ichko** [comment]
Why was this not merged?

**Pull request closed without merging**
